### ISSUE TITLE
Don't trigger prototype rules with known static methods

### ISSUE THREAD

**Issue by edg2s** [ota-meshi/eslint-plugin-es-x#36]
While prototype rules in general can't be perfect without using typescript, we can at least avoid some obvious false positives, such as flagging `Object.keys` or `Object.values` as failing `no-array-prototype-keys` and `no-array-prototype-values` respectively.

Reported downstream in Wikipedia's shared config: https://github.com/wikimedia/eslint-config-wikimedia/issues/477#issuecomment-1270673927

**Comment by ota-meshi** [comment]
I don't know what you are referring to as a problem.
The `no-array-prototype-keys` rule does not report `Object.keys` by default.

**Comment by ota-meshi** [comment]
You need to turn off aggressive mode in your config.
https://github.com/wikimedia/eslint-config-wikimedia/blob/master/common.json#L8
https://ota-meshi.github.io/eslint-plugin-es-x/#the-aggressive-mode

**Comment by edg2s** [comment]
Ping @ota-meshi .

To summarise: we get value from the Array.prototype.keys rules, but it should be able to easily ignore the obvious case of `Object.keys`, otherwise it produces too many false positives.
